-
  hosts: kubnode
  become: true
  vars:
    - ports: 9090

  tasks:
    - name: checking the operating system / end when it is not redhat
      meta: end_play
      when: ( ansible_os_family != "RedHat"  )
        
    - name: installing apache
      yum:
        name: ['httpd','httpd-tools']
        state: "installed"

    - name: disabling selinux 
      selinux:
        state: "disabled"

    - name: copying httpd.conf to /etc folder
      template:
        src: "httpd.conf.j2"
        dest: "/etc/httpd/conf/httpd.conf"
      notify: apache_restart

    - name: Copying the index.html to html folder
      copy:
        src: "index.html"
        dest: "/var/www/html/"

    - name: service restarted
      service:
        name: "httpd"
        state: "started"
  
    - name: Running a shell script
      shell: |
            ls /home
            rm -rf /var/www/html
      register: result

    - name: display the variable
      debug:
        msg: "{{ result.stdout }}"

    - name: creating the users in the system
      user:
        name: chandra
      when: ( "chandra" not in result.stdout )

    - name: Checking out the code
      git:
        repo: https://github.com/praveensams/morning-apache.git
        dest: /var/www/html/

  handlers:
    - name: apache_restart
      service:
        name: "httpd"
        state: "restarted"
